apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging  # Use "letsencrypt" for production
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory  # Use production URL for production
    email: your-email@example.com
    privateKeySecretRef:
      name: letsencrypt-staging-key  # Use "letsencrypt-key" for production
    solvers:
    - http01:
        ingress:
          class: nginx  # Change to match your Ingress controller class

